import Navbar from "@/components/Navbar";
import { Sparkles, Star } from "lucide-react";
import { Link } from "react-router-dom";

const Terms = () => {
  return (
    <div className="min-h-screen bg-background selection:bg-primary/30 selection:text-primary">
      <Navbar />

      <main className="pt-32 pb-24 px-6 mx-auto max-w-4xl min-h-[70vh]">
        <div className="inline-flex items-center gap-3 px-6 py-2 rounded-full border border-white/5 bg-white/5 text-[10px] font-black uppercase tracking-[0.4em] text-primary mb-8 animate-in fade-in duration-700">
          <BookIcon /> Legal Documentation
        </div>

        <h1 className="text-4xl md:text-6xl font-black tracking-tight mb-8 text-foreground animate-in fade-in slide-in-from-bottom-4 duration-1000">
          Terms of <span className="text-primary">Service</span>
        </h1>

        <div className="prose prose-invert prose-lg max-w-none text-muted-foreground animate-in fade-in slide-in-from-bottom-8 duration-1000 delay-200">
          <p className="text-xl font-medium mb-12 text-foreground/80">Effective Date: April 2026</p>

          <h2 className="text-2xl font-bold text-foreground mt-12 mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing or using ContentMuse ("the Platform"), an AI-powered social media generation tool, you agree to comply with and be bound by these Terms of Service. If you do not agree with any part of these terms, you must abstain from using the Platform.
          </p>

          <h2 className="text-2xl font-bold text-foreground mt-12 mb-4">2. Account Responsibilities</h2>
          <ul className="list-disc pl-6 mb-8 space-y-2">
            <li><strong>Credential Security:</strong> You are responsible for maintaining the confidentiality of your login credentials securely managed via our JWT architecture.</li>
            <li><strong>Lawful Use:</strong> You may not use the AI synthesis engine to generate malicious, illegal, or grossly offensive content.</li>
            <li><strong>API Limits:</strong> You agree to abide by generation rate limits. Abuse through bot-net interactions will result in an immediate automated ban.</li>
          </ul>

          <h2 className="text-2xl font-bold text-foreground mt-12 mb-4">3. Intellectual Property</h2>
          <p>
            Everything generated by ContentMuse strictly belongs to you, the user. However, the proprietary AI workflows, prompt architecture, UI/UX designs, and the underlying Muse v2 Engine codebase remain the exclusive intellectual property of ContentMuse.
          </p>

          <h2 className="text-2xl font-bold text-foreground mt-12 mb-4">4. Limitation of Liability</h2>
          <p>
            ContentMuse leverages state-of-the-art third-party Neural Engines (such as Groq Llama 3.3). We do not guarantee continuous uptime or absolute factual accuracy in AI-generated assets. ContentMuse shall not be held liable for any damages resulting directly or indirectly from your deployment of the generated social content.
          </p>
        </div>
      </main>

      <footer className="border-t border-border bg-card/50 pt-16 pb-10 px-6 mt-12">
        <div className="mx-auto max-w-7xl">
          <div className="flex flex-col md:flex-row items-center justify-between gap-6 mb-12">
            <Link to="/" className="flex items-center gap-2">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-primary shadow-lg shadow-primary/30">
                <Sparkles className="h-6 w-6 text-white" />
              </div>
              <span className="text-2xl font-black tracking-tight text-foreground">ContentMuse</span>
            </Link>
            <div className="flex items-center gap-6 text-sm font-semibold max-w-md w-full justify-end">
                <Link to="/privacy" className="hover:text-primary transition-colors text-muted-foreground">Privacy</Link>
                <Link to="/contact" className="hover:text-primary transition-colors text-muted-foreground">Support</Link>
                <Link to="/login" className="hover:text-primary transition-colors text-muted-foreground">Login</Link>
            </div>
          </div>
          <div className="pt-8 border-t border-border flex flex-col md:flex-row items-center justify-between gap-4">
            <p className="text-sm text-muted-foreground font-medium">© 2026 ContentMuse. All rights reserved.</p>
            <div className="flex items-center gap-6 text-muted-foreground">
              <Star className="h-5 w-5 hover:text-amber-400 cursor-pointer" />
              <Star className="h-5 w-5 hover:text-amber-400 cursor-pointer" />
              <Star className="h-5 w-5 hover:text-amber-400 cursor-pointer" />
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
};

const BookIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20"/>
  </svg>
);

export default Terms;
